#!/usr/bin/env node

const Ora = require('ora')
const program = require('commander')
const prompt = require('inquirer').createPromptModule()
const path = require('path')
const fs = require('fs')
const { exec, execSync } = require('child_process')
const spinner = new Ora()
const { downloadGit } = require('./utils')
const vueTemplateUrl = 'https://github.com/micro-structure/child-desc.git'
const reactTemplateUrl = 'https://github.com/micro-structure/child-react.git'
const workDir = process.cwd()
const fse = require('fs-extra')

program
  .version(require('../package').version)
  .usage('<command> [options]')

program
  .command('init')
  .action(async () => {
    // 选择初始化 主 或 子项目
    // 主项目需要注入 config 地址
    const { type } = await prompt({
      type: 'list',
      name: 'type',
      message: '选择创建的项目类型',
      choices: ['主项目', '子项目']
    })

    const { name } = await prompt({
      type: 'input',
      name: 'name',
      message: '请输入项目名称',
      validate (val) {
        return !!val.trim()
      }
    })

    let configUrl
    let templateUrl = ''
    if (type === '主项目') {
      templateUrl = 'https://github.com/micro-structure/parent.git'
      const res = await prompt({
        type: 'input',
        name: 'configUrl',
        message: '请输入项目配置文件绝对地址',
        validate (val) {
          return !!val.trim()
        }
      })
      configUrl = res.configUrl
    } else {
      // 选择子项目
      const { childType } = await prompt({
        type: 'list',
        name: 'childType',
        message: '选择模版',
        choices: ['vue', 'react']
      })
      templateUrl = childType === 'vue' ? vueTemplateUrl : reactTemplateUrl
    }
    spinner.start('下载模版')
    await downloadGit(templateUrl, name)
    if (configUrl) {
      const indexPath = path.resolve(workDir, name, 'public', 'index.html')
      const indexContent = fs.readFileSync(indexPath, 'utf8')
      const matches = indexContent.replace(/<\!--config path-->([\S\s]+?)<\!--config path-->/, (str, match) => {
        return '<!--config path-->\n    <script src="'+ configUrl +'"></script>\n    <!--config path-->'
      })
      fs.writeFileSync(indexPath, matches, 'utf8')
    }
    // 修改 chunk-vendors
    const vueConfigPath = path.resolve(workDir, name, 'vue.config.js')
    const vueConfigContent = fs.readFileSync(vueConfigPath, 'utf8')
    fs.writeFileSync(vueConfigPath, vueConfigContent.replace('chunk-vendors', `chunk-vendors-${name}`), 'utf8')

    spinner.succeed('下载模版成功')
    process.exit(0)
  })

program
  .command('print')
  .option('-n, --noCommit [noCommit]', '只收集依赖，不提交git')
  .action(async (cmd) => {
    const dirs = fs.readdirSync(path.resolve(workDir, 'dist'))
    const p = ['js', 'css']
    let names = []
    const result = []
    dirs.forEach(dir => {
      if (p.includes(dir)) {
        names = names.concat(fs.readdirSync(path.resolve(workDir, 'dist', dir)))
      }
    })

    const appCss = names.find(x => /^app.*?css$/.test(x))
    const chunkCss = names.find(x => /^chunk-vendors.*?css$/.test(x))
    const urlPath = names.find(x => /^app.*?js$/.test(x))
    const chunkPath = names.find(x => /^chunk-vendors.*?js$/.test(x))

    appCss && result.push(`/css/${appCss}`)
    chunkCss && result.push(`/css/${chunkCss}`)
    urlPath && result.push(`/js/${urlPath}`)
    chunkPath && result.push(`/js/${chunkPath}`)

    // 查找路由配置
    const tsRouterPath = path.resolve(workDir, 'src/routes/config.ts')
    const jsRouterPath = path.resolve(workDir, 'src/routes/config.js')
    let routerFromChild = false
    let routerFromChildContent = ''
    if (fse.pathExistsSync(tsRouterPath)) {
      routerFromChildContent = fs.readFileSync(tsRouterPath, 'utf8')
    } else if (fse.pathExistsSync(jsRouterPath)) {
      routerFromChildContent = fs.readFileSync(jsRouterPath, 'utf8')
    }
    routerFromChildContent = routerFromChildContent.replace('export default ', '')
    if (routerFromChildContent && routerFromChildContent[1]) {
      routerFromChild = true
    } else {
      routerFromChildContent = ''
    }

    spinner.info(JSON.stringify(result, null, 2))
    // 生成 index.js 文件
    const tpl = fs.readFileSync(path.resolve(__dirname, 'load.js'), 'utf8')
    const targetPath = path.resolve(workDir, 'dist', require(path.resolve(workDir, 'package.json')).version, 'index.js')
    fse.outputFileSync(
      targetPath,
      tpl
        .replace('{{ projectName }}', `"entry-${path.basename(workDir)}",`)
        .replace('{{ assetsArr }}', JSON.stringify(result, null, 2))
        .replace('{{ routerFromChild }}', String(routerFromChild))
        .replace('{{ routerFromChildContent }}', routerFromChildContent)
    )

    if (!cmd.noCommit) {
      // 提交 git
      spinner.start('文件生成成功，提交改动...\n')
      execSync('git add .')
      try {
        execSync('git commit -m "fix: regenerator index.js"')
        execSync('git push')
        spinner.succeed('提交成功\n')
      } catch (e) {
      }
      spinner.info(targetPath)
    } else {
      spinner.succeed(`引用依赖更新成功！${targetPath}`)
    }
  })

program
  .command('prebuild')
  .action(async () => {
    exec(`mv ${path.resolve(workDir, 'public')} ${path.resolve(workDir, 'public-tmp')}`, (err) => {
      if (err)
        throw err
    })
  })

program
  .command('postbuild')
  .action(async () => {
    exec(`mv ${path.resolve(workDir, 'public-tmp')} ${path.resolve(workDir, 'public')}`, (err) => {
      if (err)
        throw err
    })
  })

program.parse(process.argv)
